/**
 * ui/dist/index.html → src/ui/assets.ts. The Worker has no filesystem and tsc
 * cannot import .html, so the built page travels as a string constant in a
 * generated module that every program (tsc, vitest, wrangler) imports alike.
 * Generated and gitignored; `npm run build:ui` is the only writer.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const html = readFileSync("ui/dist/index.html", "utf8");
if (!/^<!doctype html>/i.test(html.trimStart())) {
  throw new Error("ui/dist/index.html is not an HTML document; did the Vite build run?");
}
mkdirSync("src/ui", { recursive: true });
writeFileSync(
  "src/ui/assets.ts",
  "// GENERATED by scripts/wrap-ui.ts from ui/dist/index.html. Do not edit, do not commit.\n" +
    `export const APP_HTML: string = ${JSON.stringify(html)};\n`,
);
console.error(`wrap-ui: src/ui/assets.ts, ${html.length} characters`);
