/**
 * ui/dist/index.html → src/ui/assets.ts. The Worker has no filesystem and tsc
 * cannot import .html, so the built page travels as a string constant in a
 * generated module that every program (tsc, vitest, wrangler) imports alike.
 * Generated and gitignored; `npm run build:ui` is the only writer.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";

const html = readFileSync("ui/dist/index.html", "utf8");
if (!/^<!doctype html>/i.test(html.trimStart())) {
  throw new Error("ui/dist/index.html is not an HTML document; did the Vite build run?");
}
const out = "src/ui/assets.ts";
const next =
  "// GENERATED by scripts/wrap-ui.ts from ui/dist/index.html. Do not edit, do not commit.\n" +
  `export const APP_HTML: string = ${JSON.stringify(html)};\n`;
mkdirSync("src/ui", { recursive: true });
// Write only on change. wrangler's [build] runs this and watches src/, so an
// unconditional write would wake the watcher that re-runs it, forever.
if (existsSync(out) && readFileSync(out, "utf8") === next) {
  console.error(`wrap-ui: ${out} unchanged`);
} else {
  writeFileSync(out, next);
  console.error(`wrap-ui: ${out}, ${html.length} characters`);
}
